package com.wlz.common.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Info.proto

public final class Info {
  private Info() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfoBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InfoBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 doorSerial = 1;</code>
     */
    boolean hasDoorSerial();
    /**
     * <code>required int32 doorSerial = 1;</code>
     */
    int getDoorSerial();

    /**
     * <code>required string assetCode = 2;</code>
     */
    boolean hasAssetCode();
    /**
     * <code>required string assetCode = 2;</code>
     */
    String getAssetCode();
    /**
     * <code>required string assetCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getAssetCodeBytes();

    /**
     * <code>optional string deviceIMEI = 3;</code>
     */
    boolean hasDeviceIMEI();
    /**
     * <code>optional string deviceIMEI = 3;</code>
     */
    String getDeviceIMEI();
    /**
     * <code>optional string deviceIMEI = 3;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIMEIBytes();

    /**
     * <code>optional string deviceSn = 4;</code>
     */
    boolean hasDeviceSn();
    /**
     * <code>optional string deviceSn = 4;</code>
     */
    String getDeviceSn();
    /**
     * <code>optional string deviceSn = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceSnBytes();

    /**
     * <code>required string deviceIp = 5;</code>
     */
    boolean hasDeviceIp();
    /**
     * <code>required string deviceIp = 5;</code>
     */
    String getDeviceIp();
    /**
     * <code>required string deviceIp = 5;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIpBytes();

    /**
     * <code>required int32 online = 6;</code>
     */
    boolean hasOnline();
    /**
     * <code>required int32 online = 6;</code>
     */
    int getOnline();

    /**
     * <code>required string worksite = 7;</code>
     */
    boolean hasWorksite();
    /**
     * <code>required string worksite = 7;</code>
     */
    String getWorksite();
    /**
     * <code>required string worksite = 7;</code>
     */
    com.google.protobuf.ByteString
        getWorksiteBytes();

    /**
     * <code>required int32 battery = 8;</code>
     */
    boolean hasBattery();
    /**
     * <code>required int32 battery = 8;</code>
     */
    int getBattery();
  }
  /**
   * Protobuf type {@code InfoBase}
   */
  public  static final class InfoBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InfoBase)
      InfoBaseOrBuilder {
    // Use InfoBase.newBuilder() to construct.
    private InfoBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InfoBase() {
      doorSerial_ = 0;
      assetCode_ = "";
      deviceIMEI_ = "";
      deviceSn_ = "";
      deviceIp_ = "";
      online_ = 0;
      worksite_ = "";
      battery_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InfoBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              doorSerial_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              assetCode_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              deviceIMEI_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              deviceSn_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              deviceIp_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              online_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              worksite_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              battery_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Info.internal_static_InfoBase_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Info.internal_static_InfoBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InfoBase.class, Builder.class);
    }

    private int bitField0_;
    public static final int DOORSERIAL_FIELD_NUMBER = 1;
    private int doorSerial_;
    /**
     * <code>required int32 doorSerial = 1;</code>
     */
    public boolean hasDoorSerial() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 doorSerial = 1;</code>
     */
    public int getDoorSerial() {
      return doorSerial_;
    }

    public static final int ASSETCODE_FIELD_NUMBER = 2;
    private volatile Object assetCode_;
    /**
     * <code>required string assetCode = 2;</code>
     */
    public boolean hasAssetCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string assetCode = 2;</code>
     */
    public String getAssetCode() {
      Object ref = assetCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          assetCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string assetCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssetCodeBytes() {
      Object ref = assetCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        assetCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEIMEI_FIELD_NUMBER = 3;
    private volatile Object deviceIMEI_;
    /**
     * <code>optional string deviceIMEI = 3;</code>
     */
    public boolean hasDeviceIMEI() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string deviceIMEI = 3;</code>
     */
    public String getDeviceIMEI() {
      Object ref = deviceIMEI_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceIMEI_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceIMEI = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIMEIBytes() {
      Object ref = deviceIMEI_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceIMEI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICESN_FIELD_NUMBER = 4;
    private volatile Object deviceSn_;
    /**
     * <code>optional string deviceSn = 4;</code>
     */
    public boolean hasDeviceSn() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string deviceSn = 4;</code>
     */
    public String getDeviceSn() {
      Object ref = deviceSn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceSn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deviceSn = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSnBytes() {
      Object ref = deviceSn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceSn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEIP_FIELD_NUMBER = 5;
    private volatile Object deviceIp_;
    /**
     * <code>required string deviceIp = 5;</code>
     */
    public boolean hasDeviceIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string deviceIp = 5;</code>
     */
    public String getDeviceIp() {
      Object ref = deviceIp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string deviceIp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIpBytes() {
      Object ref = deviceIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ONLINE_FIELD_NUMBER = 6;
    private int online_;
    /**
     * <code>required int32 online = 6;</code>
     */
    public boolean hasOnline() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 online = 6;</code>
     */
    public int getOnline() {
      return online_;
    }

    public static final int WORKSITE_FIELD_NUMBER = 7;
    private volatile Object worksite_;
    /**
     * <code>required string worksite = 7;</code>
     */
    public boolean hasWorksite() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string worksite = 7;</code>
     */
    public String getWorksite() {
      Object ref = worksite_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          worksite_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string worksite = 7;</code>
     */
    public com.google.protobuf.ByteString
        getWorksiteBytes() {
      Object ref = worksite_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        worksite_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATTERY_FIELD_NUMBER = 8;
    private int battery_;
    /**
     * <code>required int32 battery = 8;</code>
     */
    public boolean hasBattery() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 battery = 8;</code>
     */
    public int getBattery() {
      return battery_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDoorSerial()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAssetCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOnline()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWorksite()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBattery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, doorSerial_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assetCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceIMEI_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceSn_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, online_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, worksite_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, battery_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, doorSerial_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assetCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, deviceIMEI_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceSn_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, online_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, worksite_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, battery_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InfoBase)) {
        return super.equals(obj);
      }
      InfoBase other = (InfoBase) obj;

      boolean result = true;
      result = result && (hasDoorSerial() == other.hasDoorSerial());
      if (hasDoorSerial()) {
        result = result && (getDoorSerial()
            == other.getDoorSerial());
      }
      result = result && (hasAssetCode() == other.hasAssetCode());
      if (hasAssetCode()) {
        result = result && getAssetCode()
            .equals(other.getAssetCode());
      }
      result = result && (hasDeviceIMEI() == other.hasDeviceIMEI());
      if (hasDeviceIMEI()) {
        result = result && getDeviceIMEI()
            .equals(other.getDeviceIMEI());
      }
      result = result && (hasDeviceSn() == other.hasDeviceSn());
      if (hasDeviceSn()) {
        result = result && getDeviceSn()
            .equals(other.getDeviceSn());
      }
      result = result && (hasDeviceIp() == other.hasDeviceIp());
      if (hasDeviceIp()) {
        result = result && getDeviceIp()
            .equals(other.getDeviceIp());
      }
      result = result && (hasOnline() == other.hasOnline());
      if (hasOnline()) {
        result = result && (getOnline()
            == other.getOnline());
      }
      result = result && (hasWorksite() == other.hasWorksite());
      if (hasWorksite()) {
        result = result && getWorksite()
            .equals(other.getWorksite());
      }
      result = result && (hasBattery() == other.hasBattery());
      if (hasBattery()) {
        result = result && (getBattery()
            == other.getBattery());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDoorSerial()) {
        hash = (37 * hash) + DOORSERIAL_FIELD_NUMBER;
        hash = (53 * hash) + getDoorSerial();
      }
      if (hasAssetCode()) {
        hash = (37 * hash) + ASSETCODE_FIELD_NUMBER;
        hash = (53 * hash) + getAssetCode().hashCode();
      }
      if (hasDeviceIMEI()) {
        hash = (37 * hash) + DEVICEIMEI_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceIMEI().hashCode();
      }
      if (hasDeviceSn()) {
        hash = (37 * hash) + DEVICESN_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceSn().hashCode();
      }
      if (hasDeviceIp()) {
        hash = (37 * hash) + DEVICEIP_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceIp().hashCode();
      }
      if (hasOnline()) {
        hash = (37 * hash) + ONLINE_FIELD_NUMBER;
        hash = (53 * hash) + getOnline();
      }
      if (hasWorksite()) {
        hash = (37 * hash) + WORKSITE_FIELD_NUMBER;
        hash = (53 * hash) + getWorksite().hashCode();
      }
      if (hasBattery()) {
        hash = (37 * hash) + BATTERY_FIELD_NUMBER;
        hash = (53 * hash) + getBattery();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InfoBase parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InfoBase parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InfoBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InfoBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InfoBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InfoBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InfoBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InfoBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InfoBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InfoBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InfoBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InfoBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InfoBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InfoBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InfoBase)
        InfoBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Info.internal_static_InfoBase_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Info.internal_static_InfoBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InfoBase.class, Builder.class);
      }

      // Construct using Info.InfoBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        doorSerial_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        assetCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceIMEI_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceSn_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        online_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        worksite_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        battery_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Info.internal_static_InfoBase_descriptor;
      }

      public InfoBase getDefaultInstanceForType() {
        return InfoBase.getDefaultInstance();
      }

      public InfoBase build() {
        InfoBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public InfoBase buildPartial() {
        InfoBase result = new InfoBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.doorSerial_ = doorSerial_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.assetCode_ = assetCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceIMEI_ = deviceIMEI_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceSn_ = deviceSn_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceIp_ = deviceIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.online_ = online_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.worksite_ = worksite_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.battery_ = battery_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InfoBase) {
          return mergeFrom((InfoBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InfoBase other) {
        if (other == InfoBase.getDefaultInstance()) return this;
        if (other.hasDoorSerial()) {
          setDoorSerial(other.getDoorSerial());
        }
        if (other.hasAssetCode()) {
          bitField0_ |= 0x00000002;
          assetCode_ = other.assetCode_;
          onChanged();
        }
        if (other.hasDeviceIMEI()) {
          bitField0_ |= 0x00000004;
          deviceIMEI_ = other.deviceIMEI_;
          onChanged();
        }
        if (other.hasDeviceSn()) {
          bitField0_ |= 0x00000008;
          deviceSn_ = other.deviceSn_;
          onChanged();
        }
        if (other.hasDeviceIp()) {
          bitField0_ |= 0x00000010;
          deviceIp_ = other.deviceIp_;
          onChanged();
        }
        if (other.hasOnline()) {
          setOnline(other.getOnline());
        }
        if (other.hasWorksite()) {
          bitField0_ |= 0x00000040;
          worksite_ = other.worksite_;
          onChanged();
        }
        if (other.hasBattery()) {
          setBattery(other.getBattery());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDoorSerial()) {
          return false;
        }
        if (!hasAssetCode()) {
          return false;
        }
        if (!hasDeviceIp()) {
          return false;
        }
        if (!hasOnline()) {
          return false;
        }
        if (!hasWorksite()) {
          return false;
        }
        if (!hasBattery()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InfoBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InfoBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int doorSerial_ ;
      /**
       * <code>required int32 doorSerial = 1;</code>
       */
      public boolean hasDoorSerial() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 doorSerial = 1;</code>
       */
      public int getDoorSerial() {
        return doorSerial_;
      }
      /**
       * <code>required int32 doorSerial = 1;</code>
       */
      public Builder setDoorSerial(int value) {
        bitField0_ |= 0x00000001;
        doorSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 doorSerial = 1;</code>
       */
      public Builder clearDoorSerial() {
        bitField0_ = (bitField0_ & ~0x00000001);
        doorSerial_ = 0;
        onChanged();
        return this;
      }

      private Object assetCode_ = "";
      /**
       * <code>required string assetCode = 2;</code>
       */
      public boolean hasAssetCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string assetCode = 2;</code>
       */
      public String getAssetCode() {
        Object ref = assetCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            assetCode_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string assetCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAssetCodeBytes() {
        Object ref = assetCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          assetCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string assetCode = 2;</code>
       */
      public Builder setAssetCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        assetCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string assetCode = 2;</code>
       */
      public Builder clearAssetCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        assetCode_ = getDefaultInstance().getAssetCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string assetCode = 2;</code>
       */
      public Builder setAssetCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        assetCode_ = value;
        onChanged();
        return this;
      }

      private Object deviceIMEI_ = "";
      /**
       * <code>optional string deviceIMEI = 3;</code>
       */
      public boolean hasDeviceIMEI() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string deviceIMEI = 3;</code>
       */
      public String getDeviceIMEI() {
        Object ref = deviceIMEI_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceIMEI_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string deviceIMEI = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIMEIBytes() {
        Object ref = deviceIMEI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceIMEI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceIMEI = 3;</code>
       */
      public Builder setDeviceIMEI(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceIMEI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceIMEI = 3;</code>
       */
      public Builder clearDeviceIMEI() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceIMEI_ = getDefaultInstance().getDeviceIMEI();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceIMEI = 3;</code>
       */
      public Builder setDeviceIMEIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceIMEI_ = value;
        onChanged();
        return this;
      }

      private Object deviceSn_ = "";
      /**
       * <code>optional string deviceSn = 4;</code>
       */
      public boolean hasDeviceSn() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string deviceSn = 4;</code>
       */
      public String getDeviceSn() {
        Object ref = deviceSn_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceSn_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string deviceSn = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceSnBytes() {
        Object ref = deviceSn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceSn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceSn = 4;</code>
       */
      public Builder setDeviceSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceSn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceSn = 4;</code>
       */
      public Builder clearDeviceSn() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceSn_ = getDefaultInstance().getDeviceSn();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceSn = 4;</code>
       */
      public Builder setDeviceSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceSn_ = value;
        onChanged();
        return this;
      }

      private Object deviceIp_ = "";
      /**
       * <code>required string deviceIp = 5;</code>
       */
      public boolean hasDeviceIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string deviceIp = 5;</code>
       */
      public String getDeviceIp() {
        Object ref = deviceIp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceIp_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string deviceIp = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIpBytes() {
        Object ref = deviceIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string deviceIp = 5;</code>
       */
      public Builder setDeviceIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceIp = 5;</code>
       */
      public Builder clearDeviceIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceIp_ = getDefaultInstance().getDeviceIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string deviceIp = 5;</code>
       */
      public Builder setDeviceIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        deviceIp_ = value;
        onChanged();
        return this;
      }

      private int online_ ;
      /**
       * <code>required int32 online = 6;</code>
       */
      public boolean hasOnline() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 online = 6;</code>
       */
      public int getOnline() {
        return online_;
      }
      /**
       * <code>required int32 online = 6;</code>
       */
      public Builder setOnline(int value) {
        bitField0_ |= 0x00000020;
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 online = 6;</code>
       */
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000020);
        online_ = 0;
        onChanged();
        return this;
      }

      private Object worksite_ = "";
      /**
       * <code>required string worksite = 7;</code>
       */
      public boolean hasWorksite() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string worksite = 7;</code>
       */
      public String getWorksite() {
        Object ref = worksite_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            worksite_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string worksite = 7;</code>
       */
      public com.google.protobuf.ByteString
          getWorksiteBytes() {
        Object ref = worksite_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          worksite_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string worksite = 7;</code>
       */
      public Builder setWorksite(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        worksite_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string worksite = 7;</code>
       */
      public Builder clearWorksite() {
        bitField0_ = (bitField0_ & ~0x00000040);
        worksite_ = getDefaultInstance().getWorksite();
        onChanged();
        return this;
      }
      /**
       * <code>required string worksite = 7;</code>
       */
      public Builder setWorksiteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        worksite_ = value;
        onChanged();
        return this;
      }

      private int battery_ ;
      /**
       * <code>required int32 battery = 8;</code>
       */
      public boolean hasBattery() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 battery = 8;</code>
       */
      public int getBattery() {
        return battery_;
      }
      /**
       * <code>required int32 battery = 8;</code>
       */
      public Builder setBattery(int value) {
        bitField0_ |= 0x00000080;
        battery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 battery = 8;</code>
       */
      public Builder clearBattery() {
        bitField0_ = (bitField0_ & ~0x00000080);
        battery_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InfoBase)
    }

    // @@protoc_insertion_point(class_scope:InfoBase)
    private static final InfoBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InfoBase();
    }

    public static InfoBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<InfoBase>
        PARSER = new com.google.protobuf.AbstractParser<InfoBase>() {
      public InfoBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InfoBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InfoBase> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InfoBase> getParserForType() {
      return PARSER;
    }

    public InfoBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InfoBase_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InfoBase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nInfo.proto\"\234\001\n\010InfoBase\022\022\n\ndoorSerial\030" +
      "\001 \002(\005\022\021\n\tassetCode\030\002 \002(\t\022\022\n\ndeviceIMEI\030\003" +
      " \001(\t\022\020\n\010deviceSn\030\004 \001(\t\022\020\n\010deviceIp\030\005 \002(\t" +
      "\022\016\n\006online\030\006 \002(\005\022\020\n\010worksite\030\007 \002(\t\022\017\n\007ba" +
      "ttery\030\010 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InfoBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InfoBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InfoBase_descriptor,
        new String[] { "DoorSerial", "AssetCode", "DeviceIMEI", "DeviceSn", "DeviceIp", "Online", "Worksite", "Battery", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
